### PR TITLE
useResetAtom in utils

### LINKED ISSUE #41: Is it possible to reset the atom to its original default value?
My main goal here is to discuss about it if there's no core functionality or util that does it.

### PR DESCRIPTION
**Pull request by dai-shi**
Close #41 

- [x] snippet example
- [x] codesandbox example
- [x] docs/utils.md

### CODE REVIEW

**Comment by dai-shi** [comment]
@italodeandra Could you please try this (the sandbox above), and possibly create an example for docs? (will put the snippet and the link in docs/utils.md)

**Comment by italodeandra** [comment]
Hi @dai-shi, thank you very much for doing this.

Later today after work I'll try and create an example for the docs.

**Comment by italodeandra** [comment]
If you have any change suggestions, let me know. This was the simplest use case that I could think of.

**Snippet**
```tsx
import { useAtom } from 'jotai'
import { atomWithReset, useResetAtom } from 'jotai/utils'

const todoListAtom = atomWithReset([{
  description: "Add a todo",
  checked: false
}])

const TodoList = () => {
  const [todoList, setTodoList] = useAtom(todoListAtom)
  const resetTodoList = useResetAtom(todoListAtom)

  return (
    <>
      <ul>
        {todoList.map((todo) => (
          <li>{todo.description}</li>
        ))}
      </ul>

      <button
        onClick={() => setTodoList((l) => [ ...l, {
          description: `New todo ${new Date().toDateString()}`,
          checked: false
        }])}
      >Add todo
      </button>
      <button onClick={resetTodoList}>Reset</button>
    </>
  )
}
```

**Typescript Sandbox**
https://codesandbox.io/s/react-typescript-forked-w91cq

**Comment by dai-shi** [comment]
Looks great. Thanks!

**Pull request merged**
